export const TODOS_ADD = 'TODOS_ADD'
export const TODOS_DEL = 'TODOS_DEL'
export const TODOS_CHANGE_DONE = 'CHANGE_DONE'
export const TODOS_ALL_CHECKED = 'TODOS_ALL_CHECKED'
export const TODOS_CHANGE_NAME = 'TODOS_CHANGE_NAME'
export const TODOS_CLEAR_COMPLETED = 'TODOS_CLEAR_COMPLETED'

export const FILTERS_CHANGE_FILTER_CONDITION = 'FILTERS_CHANGE_FILTER_CONDITION'
